export type Locale = "hu" | "en" | "hr" | "ro";

export type DemoService = {
  icon: string;
  title: string;
  desc: string;
  price: string;
};

export type DemoReview = {
  name: string;
  role: string;
  text: string;
  rating: number;
};

export type DemoWhyUs = {
  icon: string;
  title: string;
  desc: string;
};

export type DemoFaq = {
  q: string;
  a: string;
};

export type DemoContent = {
  businessName: string;
  ownerName: string;
  profession: string;
  tagline: string;
  heroSubtitle: string;
  ctaText: string;
  ctaPhone: string;
  phone: string;
  email: string;
  address: string;
  mapQuery: string;
  hours: string[];
  services: DemoService[];
  reviews: DemoReview[];
  ratingScore: string;
  ratingCount: string;
  whyUs: DemoWhyUs[];
  faq: DemoFaq[];
  aboutTitle: string;
  aboutText: string;
  navServices: string;
  navAbout: string;
  navReviews: string;
  navFaq: string;
  navContact: string;
  sectionWhyUs: string;
  sectionAbout: string;
  sectionServices: string;
  sectionReviews: string;
  sectionFaq: string;
  sectionContact: string;
  contactFormTitle: string;
  contactFormSubmit: string;
  contactFormSuccess: string;
  bannerText: string;
  bannerCta: string;
};

export type DemoTheme = {
  heroBg: string;
  heroText: string;
  accentText: string;
  accentBg: string;
  accentHover: string;
  accentLight: string;
  accentBorder: string;
  iconBg: string;
  iconText: string;
  footerBg: string;
  contactBg: string;
};

export type Demo = {
  slug: string;
  emoji: string;
  heroImageUrl: string;
  galleryLabel: Record<Locale, { type: string; name: string }>;
  theme: DemoTheme;
  content: Record<Locale, DemoContent>;
};

export const themes: Record<string, DemoTheme> = {
  rose: {
    heroBg: "bg-gradient-to-br from-rose-50 via-pink-50 to-fuchsia-50",
    heroText: "text-rose-900",
    accentText: "text-rose-600",
    accentBg: "bg-rose-600",
    accentHover: "hover:bg-rose-500",
    accentLight: "bg-rose-50",
    accentBorder: "border-rose-200",
    iconBg: "bg-rose-100",
    iconText: "text-rose-600",
    footerBg: "bg-rose-950",
    contactBg: "bg-rose-900",
  },
  amber: {
    heroBg: "bg-gradient-to-br from-amber-50 via-orange-50 to-yellow-50",
    heroText: "text-amber-900",
    accentText: "text-amber-600",
    accentBg: "bg-amber-600",
    accentHover: "hover:bg-amber-500",
    accentLight: "bg-amber-50",
    accentBorder: "border-amber-200",
    iconBg: "bg-amber-100",
    iconText: "text-amber-600",
    footerBg: "bg-amber-950",
    contactBg: "bg-amber-900",
  },
  teal: {
    heroBg: "bg-gradient-to-br from-teal-50 via-emerald-50 to-cyan-50",
    heroText: "text-teal-900",
    accentText: "text-teal-600",
    accentBg: "bg-teal-600",
    accentHover: "hover:bg-teal-500",
    accentLight: "bg-teal-50",
    accentBorder: "border-teal-200",
    iconBg: "bg-teal-100",
    iconText: "text-teal-600",
    footerBg: "bg-teal-950",
    contactBg: "bg-teal-900",
  },
  blue: {
    heroBg: "bg-gradient-to-br from-blue-50 via-sky-50 to-indigo-50",
    heroText: "text-blue-900",
    accentText: "text-blue-600",
    accentBg: "bg-blue-600",
    accentHover: "hover:bg-blue-500",
    accentLight: "bg-blue-50",
    accentBorder: "border-blue-200",
    iconBg: "bg-blue-100",
    iconText: "text-blue-600",
    footerBg: "bg-blue-950",
    contactBg: "bg-blue-900",
  },
};

export const demos: Demo[] = [
  // ─── CUKRÁSZDA ──────────────────────────────────────────────────────────────
  {
    slug: "cukraszda",
    emoji: "🎂",
    heroImageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1400&q=80",
    galleryLabel: {
      hu: { type: "Cukrászda", name: "Édes Percek" },
      en: { type: "Pastry shop", name: "Sweet Moments" },
      hr: { type: "Slastičarna", name: "Slatki Trenuci" },
      ro: { type: "Cofetărie", name: "Clipe Dulci" },
    },
    theme: themes.rose,
    content: {
      hu: {
        businessName: "Édes Percek Cukrászda",
        ownerName: "Balogh Kinga",
        profession: "Cukrász mester",
        tagline: "Minden falat egy különleges pillanat.",
        heroSubtitle: "Kézzel készített torták, sütemények és desszertek Miskolcon – minden alkalomra. Személyes megrendelés, gyors elkészítés.",
        ctaText: "Rendelés most",
        ctaPhone: "Hívj most",
        phone: "+36 70 234 5678",
        email: "kinga@edespercek.hu",
        address: "Miskolc, Széchenyi utca 14.",
        mapQuery: "Miskolc, Széchenyi utca 14",
        hours: ["H–P: 9:00–18:00", "Sz: 9:00–16:00", "V: 10:00–14:00"],
        ratingScore: "4.9",
        ratingCount: "127 értékelés",
        services: [
          { icon: "cake", title: "Egyedi torták", desc: "Születésnap, esküvő, keresztelő – minden alkalomra kézzel díszített, személyre szabott torta. Konzultáció után akár 3 nap alatt elkészül.", price: "8 000 Ft/kg-tól" },
          { icon: "cookie", title: "Sütemények & finomságok", desc: "Napi friss péksütemények, krémes szeletek, macaronok, éclair-ek és szezonális édességek. Vitrines kínálatunk mindennap változik.", price: "450 Ft-tól" },
          { icon: "gift", title: "Ajándékcsomagok", desc: "Válogatott édességek díszdobozban – céges ajándéknak, születésnapra, ünnepre. Saját felirattal, szalaggal is kérhető.", price: "3 500 Ft-tól" },
        ],
        reviews: [
          { name: "Szabó Eszter", role: "Esküvős menyasszony", text: "Az esküvői tortánk tökéletes volt – pontosan olyan, ahogyan elképzeltük. Mindenki kérdezte, honnan van! Kinga türelmes és precíz, igazi szakember.", rating: 5 },
          { name: "Fekete Ádám", role: "HR Menedzser", text: "Céges rendezvényre rendeltem 10 darab ajándékcsomagot. Profi csomagolás, mennyei ízek, mindenki oda volt érte. Legközelebb is itt rendelek.", rating: 5 },
          { name: "Horváth Lili", role: "Édesanya", text: "A gyermekem születésnapjára rendeltünk tortát. Kinga csodát tett – az egész parti a tortáról szólt! Pontos szállítás, tökéletes megvalósítás.", rating: 5 },
        ],
        whyUs: [
          { icon: "heart", title: "Szívvel-lélekkel", desc: "Minden tortát és süteményt személyesen készítek és díszítek – alvállalkozó nélkül, kézzel." },
          { icon: "leaf", title: "Friss alapanyagok", desc: "Naponta frissen érkező prémium alapanyagok: hazai tojás, vajkrém, szezonális gyümölcsök." },
          { icon: "star", title: "Személyre szabott", desc: "Minden rendelés egyedi – az ízektől a díszítésig pontosan az elképzelésed szerint." },
          { icon: "truck", title: "Kiszállítás", desc: "Házhoz szállítunk Miskolcon és 30 km-es körzetében, biztonságos csomagolásban." },
          { icon: "gift", title: "Ajándékutalvány", desc: "Meglepetés ajándéknak: bármilyen értékű utalvány, azonnal felhasználható." },
          { icon: "clock", title: "Sürgős rendelés", desc: "Gyorsan kell? Vedd fel velünk a kapcsolatot – sokszor 24-48 órán belül is megoldjuk." },
        ],
        faq: [
          { q: "Mikor kell leadni a rendelést?", a: "Tortáknál legalább 3–5 munkanappal előre, süteményeknél 1 nappal. Sürgős esetben hívj, és megnézzük, mit tudunk tenni!" },
          { q: "Van-e gluténmentes lehetőség?", a: "Igen! Szinte minden termékünket elkészítjük gluténmentesen is. Kérjük, jelezd a megrendeléskor." },
          { q: "Hogyan fizetek?", a: "Átvételkor készpénzzel vagy bankkártyával, illetve előre utalással is lehetséges. Nagyobb rendelésekhez 30% foglalót kérünk." },
          { q: "Vállaltok-e szállítást?", a: "Igen, Miskolcon és 30 km-es körzetében. A szállítási díj 1 500–3 000 Ft, távolságtól függően." },
          { q: "Hány személyre elegendő egy torta?", a: "Általában kg-onként 8–10 szelettel számolunk. Írd meg, hány főnek készül, és segítünk a méretválasztásban." },
        ],
        aboutTitle: "Szia, Kinga vagyok!",
        aboutText: "12 éve sütök és díszítek tortákat profi szinten Miskolcon. Cukrász mestervizsgám van, de ami igazán számít: minden rendelésnél úgy dolgozom, mintha a saját esküvőmre vagy születésnapomra készíteném. Kis szalonban dolgozom, így minden ügyfelemet személyesen ismerem. Nálam nincs sablonos torta – az elképzelésedet valóra váltom.",
        navServices: "Kínálat",
        navAbout: "Rólam",
        navReviews: "Vélemények",
        navFaq: "GYIK",
        navContact: "Kapcsolat",
        sectionWhyUs: "Miért minket válassz?",
        sectionAbout: "Rólam",
        sectionServices: "Kínálatunk",
        sectionReviews: "Ügyfélvélemények",
        sectionFaq: "Gyakori kérdések",
        sectionContact: "Kapcsolat",
        contactFormTitle: "Küldj üzenetet",
        contactFormSubmit: "Üzenet küldése",
        contactFormSuccess: "Köszönjük! Hamarosan visszajelzünk.",
        bannerText: "Ez egy minta weboldal. Ilyen weboldalad is lehet.",
        bannerCta: "Kérj ajánlatot",
      },
      en: {
        businessName: "Sweet Moments Bakery",
        ownerName: "Katherine Baker",
        profession: "Master Pastry Chef",
        tagline: "Every bite is a special moment.",
        heroSubtitle: "Handcrafted cakes, pastries and desserts in York – for every occasion. Personal orders, quick turnaround.",
        ctaText: "Order now",
        ctaPhone: "Call now",
        phone: "+44 7700 234567",
        email: "katherine@sweetmoments.co.uk",
        address: "14 High Street, York",
        mapQuery: "14 High Street, York, UK",
        hours: ["Mon–Fri: 9:00–18:00", "Sat: 9:00–16:00", "Sun: 10:00–14:00"],
        ratingScore: "4.9",
        ratingCount: "127 reviews",
        services: [
          { icon: "cake", title: "Custom cakes", desc: "Birthday, wedding, christening – handcrafted cakes designed to order. Ready in as little as 3 days after consultation.", price: "From £8/slice" },
          { icon: "cookie", title: "Pastries & treats", desc: "Fresh daily pastries, cream slices, macarons, éclairs and seasonal specials. Our display changes every day.", price: "From £3" },
          { icon: "gift", title: "Gift boxes", desc: "Curated sweets in a decorative gift box – perfect for corporate gifts, birthdays or celebrations. Custom ribbons available.", price: "From £22" },
        ],
        reviews: [
          { name: "Sarah Williams", role: "Bride", text: "Our wedding cake was absolutely perfect – exactly as we imagined. Everyone asked where it came from! Katherine is patient and precise, a true professional.", rating: 5 },
          { name: "Adam Black", role: "HR Manager", text: "I ordered 10 gift boxes for a corporate event. Professional packaging, divine flavours – everyone was amazed. I'll order here again.", rating: 5 },
          { name: "Lily Hart", role: "Mum", text: "Ordered a birthday cake for my daughter. Katherine worked magic – the whole party was about the cake! Perfect delivery, flawless execution.", rating: 5 },
        ],
        whyUs: [
          { icon: "heart", title: "Made with love", desc: "Every cake and pastry is personally made and decorated by me – no subcontractors, all handmade." },
          { icon: "leaf", title: "Fresh ingredients", desc: "Premium ingredients arriving fresh daily: free-range eggs, butter cream, seasonal fruits." },
          { icon: "star", title: "Personalised", desc: "Every order is unique – from flavours to decoration, crafted exactly to your vision." },
          { icon: "truck", title: "Delivery", desc: "We deliver across York and within 20 miles, safely packaged." },
          { icon: "gift", title: "Gift vouchers", desc: "The perfect surprise: gift vouchers in any amount, ready to use immediately." },
          { icon: "clock", title: "Rush orders", desc: "Need it fast? Get in touch – we can often deliver in 24–48 hours." },
        ],
        faq: [
          { q: "When do I need to order by?", a: "For cakes, at least 3–5 working days ahead; for pastries, 1 day. In urgent cases, just call and we'll see what we can do!" },
          { q: "Do you offer gluten-free options?", a: "Yes! Almost all our products can be made gluten-free. Please let us know when ordering." },
          { q: "How do I pay?", a: "On collection by cash or card, or in advance by bank transfer. A 30% deposit is required for larger orders." },
          { q: "Do you deliver?", a: "Yes, across York and within 20 miles. Delivery fee is £5–£15 depending on distance." },
          { q: "How many servings per cake?", a: "We generally calculate 8–10 slices per kg. Tell us how many guests and we'll help you choose the right size." },
        ],
        aboutTitle: "Hi, I'm Katherine!",
        aboutText: "I've been baking and decorating cakes professionally in York for 12 years. I have a master pastry qualification, but what really matters is that I put my heart into every single order. I work in a small studio, so I know every client personally. No template cakes here – I bring your vision to life.",
        navServices: "Menu",
        navAbout: "About",
        navReviews: "Reviews",
        navFaq: "FAQ",
        navContact: "Contact",
        sectionWhyUs: "Why choose us?",
        sectionAbout: "About me",
        sectionServices: "What we offer",
        sectionReviews: "Customer reviews",
        sectionFaq: "Frequently asked questions",
        sectionContact: "Contact",
        contactFormTitle: "Send a message",
        contactFormSubmit: "Send message",
        contactFormSuccess: "Thank you! We'll be in touch soon.",
        bannerText: "This is a sample website. You could have one just like it.",
        bannerCta: "Get a quote",
      },
      hr: {
        businessName: "Slatki Trenuci Slastičarna",
        ownerName: "Katarina Šimić",
        profession: "Majstorica slastičarstva",
        tagline: "Svaki zalogaj poseban je trenutak.",
        heroSubtitle: "Ručno rađene torte, kolači i deserti u Zagrebu – za svaku prigodu. Osobne narudžbe, brza izrada.",
        ctaText: "Naruči odmah",
        ctaPhone: "Nazovi nas",
        phone: "+385 91 234 5678",
        email: "katarina@slatki-trenuci.hr",
        address: "Zagreb, Ilica 32",
        mapQuery: "Zagreb, Ilica 32",
        hours: ["Pon–Pet: 9:00–18:00", "Sub: 9:00–16:00", "Ned: 10:00–14:00"],
        ratingScore: "4.9",
        ratingCount: "127 recenzija",
        services: [
          { icon: "cake", title: "Individualne torte", desc: "Rođendan, vjenčanje, krštenje – ručno ukrašene, personalizirane torte za svaku prigodu. Gotove za 3 dana od konzultacije.", price: "Od 60 €/kg" },
          { icon: "cookie", title: "Kolači & slatkiši", desc: "Svježi svakodnevni kolači, kremasti rezovi, macaroni, éclairs i sezonski specijaliteti. Naš izlog mijenja se svaki dan.", price: "Od 3 €" },
          { icon: "gift", title: "Poklon kutije", desc: "Odabrani slatkiši u ukrasnoj kutiji – za poslovne darove, rođendane ili proslave. Dostupne s personaliziranom trakom.", price: "Od 25 €" },
        ],
        reviews: [
          { name: "Ana Kovač", role: "Nevjesta", text: "Naša svadbena torta bila je savršena – točno onakva kakvu smo zamislili. Svi su pitali odakle je! Katarina je strpljiva i precizna, pravi profesionalac.", rating: 5 },
          { name: "Tomislav Jurić", role: "HR Menadžer", text: "Naručio 10 poklon kutija za poslovni događaj. Profesionalno pakiranje, božanstveni okusi – svi su bili oduševljeni. Svakako opet ovdje.", rating: 5 },
          { name: "Maja Novak", role: "Mama", text: "Naručila tortu za rođendan kćerke. Katarina je napravila čudo – cijela zabava bila je o torti! Točna dostava, savršena izvedba.", rating: 5 },
        ],
        whyUs: [
          { icon: "heart", title: "Rađeno s ljubavlju", desc: "Svaku tortu i kolač osobno izrađujem i ukrašavam – bez podizvođača, sve ručno." },
          { icon: "leaf", title: "Svježi sastojci", desc: "Premium sastojci koji svakodnevno dolaze svježi: domaća jaja, maslac, sezonski voće." },
          { icon: "star", title: "Personalizirano", desc: "Svaka narudžba je jedinstvena – od okusa do ukrasa, točno prema vašoj viziji." },
          { icon: "truck", title: "Dostava", desc: "Dostavljamo po Zagrebu i u polumjeru 30 km, sigurno zapakirano." },
          { icon: "gift", title: "Poklon bon", desc: "Savršeno iznenađenje: poklon bonovi u bilo kojoj vrijednosti, odmah za korištenje." },
          { icon: "clock", title: "Hitne narudžbe", desc: "Treba vam brzo? Javite se – često možemo isporučiti za 24–48 sati." },
        ],
        faq: [
          { q: "Kada trebam naručiti?", a: "Za torte najmanje 3–5 radnih dana unaprijed, za kolače 1 dan. U hitnim slučajevima nazovite i vidjet ćemo što možemo učiniti!" },
          { q: "Imate li opciju bez glutena?", a: "Da! Gotovo sve naše proizvode možemo izraditi bez glutena. Molimo navedite to pri narudžbi." },
          { q: "Kako plaćam?", a: "Pri preuzimanju gotovinom ili karticom, ili unaprijed bankovnim transferom. Za veće narudžbe tražimo 30% predujam." },
          { q: "Dostavljate li?", a: "Da, po Zagrebu i u polumjeru 30 km. Cijena dostave je 10–25 € ovisno o udaljenosti." },
          { q: "Koliko porcija ima jedna torta?", a: "Računamo otprilike 8–10 kriški po kilogramu. Recite nam za koliko gostiju i pomoći ćemo vam odabrati pravu veličinu." },
        ],
        aboutTitle: "Bok, ja sam Katarina!",
        aboutText: "Profesionalno pečem i ukrašavam torte u Zagrebu već 12 godina. Imam majstorsku kvalifikaciju slastičara, ali ono što je zaista važno: u svaku narudžbu ulažem srce. Radim u malom studiju, pa osobno poznajem svakog klijenta. Nema standardnih torti – ostvarujem vaše vizije.",
        navServices: "Ponuda",
        navAbout: "O meni",
        navReviews: "Recenzije",
        navFaq: "FAQ",
        navContact: "Kontakt",
        sectionWhyUs: "Zašto nas odabrati?",
        sectionAbout: "O meni",
        sectionServices: "Što nudimo",
        sectionReviews: "Recenzije klijenata",
        sectionFaq: "Često postavljana pitanja",
        sectionContact: "Kontakt",
        contactFormTitle: "Pošaljite poruku",
        contactFormSubmit: "Pošalji poruku",
        contactFormSuccess: "Hvala! Javit ćemo se uskoro.",
        bannerText: "Ovo je primjer web stranice. I vi možete imati ovakvu.",
        bannerCta: "Zatražite ponudu",
      },
      ro: {
        businessName: "Clipe Dulci Cofetărie",
        ownerName: "Cristina Moldovan",
        profession: "Maistru cofetar",
        tagline: "Fiecare îmbucătură e un moment special.",
        heroSubtitle: "Torturi, prăjituri și deserturi lucrate manual în Cluj – pentru orice ocazie. Comenzi personalizate, livrare rapidă.",
        ctaText: "Comandă acum",
        ctaPhone: "Sună acum",
        phone: "+40 721 234 567",
        email: "cristina@clipedulci.ro",
        address: "Cluj-Napoca, Str. Eroilor 14",
        mapQuery: "Cluj-Napoca, Str. Eroilor 14",
        hours: ["Lun–Vin: 9:00–18:00", "Sâm: 9:00–16:00", "Dum: 10:00–14:00"],
        ratingScore: "4.9",
        ratingCount: "127 recenzii",
        services: [
          { icon: "cake", title: "Torturi personalizate", desc: "Zi de naștere, nuntă, botez – torturi decorate manual, personalizate pentru fiecare ocazie. Gata în 3 zile după consultație.", price: "De la 120 lei/kg" },
          { icon: "cookie", title: "Prăjituri & delicii", desc: "Prăjituri proaspete zilnic, felii cu cremă, macarons, éclairs și specialități sezoniere. Vitrina noastră se schimbă în fiecare zi.", price: "De la 12 lei" },
          { icon: "gift", title: "Cutii cadou", desc: "Dulciuri alese în cutii decorative – cadouri corporate, zile de naștere sau sărbători. Disponibile cu panglică personalizată.", price: "De la 80 lei" },
        ],
        reviews: [
          { name: "Ioana Popa", role: "Mireasă", text: "Tortul de nuntă a fost perfect – exact cum am visat. Toți au întrebat de unde e! Cristina e răbdătoare și precisă, un adevărat profesionist.", rating: 5 },
          { name: "Bogdan Rusu", role: "Manager HR", text: "Am comandat 10 cutii cadou pentru un eveniment de business. Ambalaj profesional, gusturi divine – toți au fost impresionați. Cu siguranță comand din nou.", rating: 5 },
          { name: "Raluca Stan", role: "Mămică", text: "Am comandat tort pentru ziua fiicei mele. Cristina a făcut minuni – toată petrecerea a fost despre tort! Livrare punctuală, execuție perfectă.", rating: 5 },
        ],
        whyUs: [
          { icon: "heart", title: "Făcut cu dragoste", desc: "Fiecare tort și prăjitură le pregătesc și decorez personal – fără subcontractori, totul manual." },
          { icon: "leaf", title: "Ingrediente proaspete", desc: "Ingrediente premium care sosesc proaspete zilnic: ouă de casă, unt, fructe de sezon." },
          { icon: "star", title: "Personalizat", desc: "Fiecare comandă e unică – de la arome la decorațiuni, exact după viziunea ta." },
          { icon: "truck", title: "Livrare", desc: "Livrăm în Cluj-Napoca și în raza de 30 km, ambalat în siguranță." },
          { icon: "gift", title: "Vouchere cadou", desc: "Surpriza perfectă: vouchere cadou de orice valoare, folosibile imediat." },
          { icon: "clock", title: "Comenzi urgente", desc: "Ai nevoie urgent? Contactează-ne – deseori putem livra în 24–48 ore." },
        ],
        faq: [
          { q: "Când trebuie să comand?", a: "Pentru torturi cu cel puțin 3–5 zile lucrătoare înainte, pentru prăjituri cu 1 zi. În cazuri urgente, sună și vedem ce putem face!" },
          { q: "Aveți opțiuni fără gluten?", a: "Da! Aproape toate produsele noastre pot fi preparate fără gluten. Te rugăm să specifici la comandă." },
          { q: "Cum plătesc?", a: "La ridicare cu numerar sau card, sau în avans prin transfer bancar. Pentru comenzi mari solicităm 30% avans." },
          { q: "Livrați?", a: "Da, în Cluj-Napoca și în raza de 30 km. Tariful de livrare este 15–40 lei în funcție de distanță." },
          { q: "Câte porții are un tort?", a: "Calculăm aproximativ 8–10 felii per kilogram. Spune-ne pentru câți oaspeți e și te ajutăm să alegi dimensiunea potrivită." },
        ],
        aboutTitle: "Bună, sunt Cristina!",
        aboutText: "Fac cofetărie profesional în Cluj-Napoca de 12 ani. Am calificare de maistru cofetar, dar ce contează cu adevărat este că pun suflet în fiecare comandă. Lucrez într-un studio mic, așa că îmi cunosc personal fiecare client. Nu există torturi standard la mine – îți aduc viziunea la viață.",
        navServices: "Ofertă",
        navAbout: "Despre mine",
        navReviews: "Recenzii",
        navFaq: "FAQ",
        navContact: "Contact",
        sectionWhyUs: "De ce să ne alegi?",
        sectionAbout: "Despre mine",
        sectionServices: "Ce oferim",
        sectionReviews: "Recenzii clienți",
        sectionFaq: "Întrebări frecvente",
        sectionContact: "Contact",
        contactFormTitle: "Trimite un mesaj",
        contactFormSubmit: "Trimite mesajul",
        contactFormSuccess: "Mulțumim! Te contactăm în curând.",
        bannerText: "Acesta este un site demonstrativ. Poți avea unul la fel.",
        bannerCta: "Solicită ofertă",
      },
    },
  },

  // ─── PIZZÁZÓ ────────────────────────────────────────────────────────────────
  {
    slug: "pizzazo",
    emoji: "🍕",
    heroImageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1400&q=80",
    galleryLabel: {
      hu: { type: "Pizzázó", name: "Napoli Pizzéria" },
      en: { type: "Pizza restaurant", name: "Napoli Pizzeria" },
      hr: { type: "Pizzeria", name: "Napoli Pizzeria" },
      ro: { type: "Pizzerie", name: "Napoli Pizzeria" },
    },
    theme: themes.amber,
    content: {
      hu: {
        businessName: "Napoli Pizzéria",
        ownerName: "Tóth Gábor",
        profession: "Pizzaiolo mester",
        tagline: "Igazi nápolyi pizza, szívből sütve.",
        heroSubtitle: "Kézzel nyújtott tészta, 48 órás érlelés, fából tüzelt kemence – a legjobb pizza Budapesten. Rendeld házhozszállítással vagy gyere be!",
        ctaText: "Rendelés most",
        ctaPhone: "Hívj minket",
        phone: "+36 20 345 6789",
        email: "gabor@napolipizza.hu",
        address: "Budapest, Bartók Béla út 22.",
        mapQuery: "Budapest, Bartók Béla út 22",
        hours: ["H–Cs: 11:00–22:00", "P–Sz: 11:00–23:00", "V: 12:00–21:00"],
        ratingScore: "4.8",
        ratingCount: "312 értékelés",
        services: [
          { icon: "pizza", title: "Klasszikus pizzák", desc: "Margherita, Diavola, Quattro Stagioni és még 15 féle pizza – mind fából tüzelt kemencéből sütve, 90 másodperc alatt elkészül.", price: "2 400 Ft-tól" },
          { icon: "flame", title: "Prémium pizzák", desc: "Szezonális alkotások prémium feltétekkel: fekete szarvasgomba, burrata, ibériai sonka és friss bazsalikom. Korlátozott kínálat.", price: "3 800 Ft-tól" },
          { icon: "package", title: "Házhozszállítás", desc: "Frissen sült pizza az ajtódhoz 30 percen belül. Min. rendelés 2 500 Ft, 4 500 Ft felett a szállítás ingyenes.", price: "Ingyenes 4 500 Ft felett" },
        ],
        reviews: [
          { name: "Varga Péter", role: "Törzsvendég", text: "A legjobb pizza Budapesten – ezt minden barátomnak elmondom. Az impasto tökéletes, mint Nápolyban. Hetente visszajárok. Csak azt kívánom, bővítenék a teraszát!", rating: 5 },
          { name: "Kiss Éva", role: "Gasztroblogger", text: "A fából tüzelt kemence mindent megváltoztat. Ropogós perem, szelíden sült közepe, friss feltétek. Autentikusabb pizzát Magyarországon nehéz találni.", rating: 5 },
          { name: "Molnár Bence", role: "Irodai team lead", text: "Már 2 éve rendeljük ebédre az irodába. Mindig pontosan érkezik, mindig friss és finom. Az egész csapat kedvence. Kötelező kipróbálni!", rating: 5 },
        ],
        whyUs: [
          { icon: "flame", title: "Fából tüzelt kemence", desc: "Tradicionális nápolyi technika: 485°C-os kőkemence, amelyben 90 másodperc alatt sül a pizza." },
          { icon: "clock", title: "48 órás tészta érlelés", desc: "A hosszú hideg fermentálás könnyebb, emészthetőbb, ropogósabb tésztát eredményez." },
          { icon: "leaf", title: "Olasz alapanyagok", desc: "Importált San Marzano paradicsom, DOC mozzarella, friss bazsalikom – minden Olaszországból." },
          { icon: "star", title: "Vegetáriánus választék", desc: "5 féle húsmentes pizza az étlapunkon, szezonális zöldségekkel és prémium sajtokkal." },
          { icon: "truck", title: "Házhozszállítás", desc: "30 percen belül érkezünk. Online rendelés is lehetséges az e-mailen vagy telefonon." },
          { icon: "zap", title: "Gyors kiszolgálás", desc: "Helyi fogyasztás esetén 15 percen belül asztalhoz hozzuk a frissen sült pizzát." },
        ],
        faq: [
          { q: "Mik a nyitvatartási időtök?", a: "H–Cs: 11:00–22:00, P–Sz: 11:00–23:00, V: 12:00–21:00. Ünnepnapokon esetleg eltérő nyitvatartás, ezt a Facebookon jelezzük." },
          { q: "Van-e házhozszállítás?", a: "Igen! Telefonon vagy e-mailben lehet rendelni. 30 percen belül szállítunk, 4 500 Ft felett a szállítás ingyenes." },
          { q: "Van-e vegetáriánus vagy vegán pizza?", a: "Igen, 5 féle vegetáriánus és 2 vegán pizzánk van. Kérésre laktózmentes sajttal is készítjük." },
          { q: "Lehet-e előre rendelni?", a: "Igen, akár 3 nappal előre is. Csoportos rendeléseknél (10+ pizza) érdemes előre foglalni." },
          { q: "Mi az a nápolyi pizza és miért más?", a: "A nápolyi pizza UNESCO-örökség. Jellemzői: vékony kézzel nyújtott alap, vastag, levegős perem (cornicione), és nagyon rövid sütési idő (90 mp) magas hőmérsékleten." },
        ],
        aboutTitle: "Szia, Gábor vagyok!",
        aboutText: "Nápolyban tanultam a pizzakészítés tudományát egy háromgenerációs pizzériában, és 2019-ben nyitottam meg a Napoli Pizzériát Budapesten. Ugyanazokat az elveket követem: jó olasz liszt (Caputo), hosszú hideg fermentálás, friss alapanyagok, és persze a fából tüzelt kemence. A Napoli nem egy étterem – ez egy szenvedély.",
        navServices: "Étlap",
        navAbout: "Rólunk",
        navReviews: "Vélemények",
        navFaq: "GYIK",
        navContact: "Kapcsolat",
        sectionWhyUs: "Miért a Napoli?",
        sectionAbout: "Rólunk",
        sectionServices: "Étlapunk",
        sectionReviews: "Ügyfélvélemények",
        sectionFaq: "Gyakori kérdések",
        sectionContact: "Kapcsolat & Rendelés",
        contactFormTitle: "Rendelés vagy kérdés",
        contactFormSubmit: "Üzenet küldése",
        contactFormSuccess: "Köszönjük! Hamarosan visszajelzünk.",
        bannerText: "Ez egy minta weboldal. Ilyen weboldalad is lehet.",
        bannerCta: "Kérj ajánlatot",
      },
      en: {
        businessName: "Napoli Pizzeria",
        ownerName: "Gabriel Stone",
        profession: "Master Pizzaiolo",
        tagline: "Authentic Neapolitan pizza, baked with heart.",
        heroSubtitle: "Hand-stretched dough, 48-hour fermentation, wood-fired oven – the best pizza in London. Order delivery or dine in!",
        ctaText: "Order now",
        ctaPhone: "Call us",
        phone: "+44 7800 345678",
        email: "gabriel@napolipizzeria.co.uk",
        address: "22 Brick Lane, London",
        mapQuery: "22 Brick Lane, London, UK",
        hours: ["Mon–Thu: 11:00–22:00", "Fri–Sat: 11:00–23:00", "Sun: 12:00–21:00"],
        ratingScore: "4.8",
        ratingCount: "312 reviews",
        services: [
          { icon: "pizza", title: "Classic pizzas", desc: "Margherita, Diavola, Quattro Stagioni and 15 more – all from our wood-fired oven, ready in 90 seconds.", price: "From £11" },
          { icon: "flame", title: "Premium pizzas", desc: "Seasonal creations with premium toppings: black truffle, burrata, Iberian ham and fresh basil. Limited availability.", price: "From £17" },
          { icon: "package", title: "Home delivery", desc: "Fresh pizza at your door in 30 minutes. Min. order £12, free delivery over £22.", price: "Free over £22" },
        ],
        reviews: [
          { name: "Peter Green", role: "Regular", text: "The best pizza in London – I tell everyone. The impasto is perfect, just like Naples. I come back every week. I just wish they'd expand the terrace!", rating: 5 },
          { name: "Eva Clark", role: "Food blogger", text: "The wood-fired oven changes everything. Crispy crust, gently baked centre, fresh toppings. Hard to find more authentic pizza in the UK.", rating: 5 },
          { name: "Ben Miller", role: "Office team lead", text: "We've been ordering for lunch for 2 years. Always on time, always fresh and delicious. The whole team loves it. A must-try!", rating: 5 },
        ],
        whyUs: [
          { icon: "flame", title: "Wood-fired oven", desc: "Traditional Neapolitan technique: 485°C stone oven – pizza baked in 90 seconds." },
          { icon: "clock", title: "48-hour dough", desc: "Long cold fermentation creates lighter, more digestible, crispier dough." },
          { icon: "leaf", title: "Italian ingredients", desc: "Imported San Marzano tomatoes, DOC mozzarella, fresh basil – everything from Italy." },
          { icon: "star", title: "Vegetarian options", desc: "5 meat-free pizzas on our menu, with seasonal vegetables and premium cheeses." },
          { icon: "truck", title: "Home delivery", desc: "We arrive within 30 minutes. Order online, by email or phone." },
          { icon: "zap", title: "Fast service", desc: "Dining in? Your freshly baked pizza arrives at your table within 15 minutes." },
        ],
        faq: [
          { q: "What are your opening hours?", a: "Mon–Thu: 11:00–22:00, Fri–Sat: 11:00–23:00, Sun: 12:00–21:00. We post any holiday changes on Facebook." },
          { q: "Do you do home delivery?", a: "Yes! Order by phone or email. We deliver within 30 minutes, free over £22." },
          { q: "Do you have vegetarian or vegan options?", a: "Yes, 5 vegetarian and 2 vegan pizzas. We can also make them with lactose-free cheese on request." },
          { q: "Can I pre-order?", a: "Yes, up to 3 days in advance. For group orders (10+ pizzas) we recommend booking ahead." },
          { q: "What makes Neapolitan pizza different?", a: "Neapolitan pizza is UNESCO heritage. Key features: thin hand-stretched base, thick airy crust (cornicione), and very short bake time (90 sec) at high temperature." },
        ],
        aboutTitle: "Hi, I'm Gabriel!",
        aboutText: "I learned pizza-making in Naples at a three-generation pizzeria, and in 2019 I opened Napoli Pizzeria in London. I follow the same principles: good Italian flour (Caputo), long cold fermentation, fresh ingredients, and of course the wood-fired oven. Napoli isn't a restaurant – it's a passion.",
        navServices: "Menu",
        navAbout: "About",
        navReviews: "Reviews",
        navFaq: "FAQ",
        navContact: "Contact",
        sectionWhyUs: "Why Napoli?",
        sectionAbout: "About us",
        sectionServices: "Our menu",
        sectionReviews: "Customer reviews",
        sectionFaq: "Frequently asked questions",
        sectionContact: "Contact & Orders",
        contactFormTitle: "Order or enquiry",
        contactFormSubmit: "Send message",
        contactFormSuccess: "Thank you! We'll be in touch soon.",
        bannerText: "This is a sample website. You could have one just like it.",
        bannerCta: "Get a quote",
      },
      hr: {
        businessName: "Napoli Pizzeria",
        ownerName: "Gabriele Moretti",
        profession: "Majstor pizzar",
        tagline: "Autentična napolitanska pizza, pečena iz srca.",
        heroSubtitle: "Ručno razvučeno tijesto, 48-satna fermentacija, krušna peć na drva – najukusnija pizza u Zagrebu. Naručite dostavu ili dođite k nama!",
        ctaText: "Naruči odmah",
        ctaPhone: "Nazovite nas",
        phone: "+385 91 345 6789",
        email: "gabriele@napolipizzeria.hr",
        address: "Zagreb, Tratinska 22",
        mapQuery: "Zagreb, Tratinska 22",
        hours: ["Pon–Čet: 11:00–22:00", "Pet–Sub: 11:00–23:00", "Ned: 12:00–21:00"],
        ratingScore: "4.8",
        ratingCount: "312 recenzija",
        services: [
          { icon: "pizza", title: "Klasične pizze", desc: "Margherita, Diavola, Quattro Stagioni i još 15 vrsta – sve iz peći na drva, gotovo za 90 sekundi.", price: "Od 12 €" },
          { icon: "flame", title: "Premium pizze", desc: "Sezonske kreacije s premium dodacima: crni tartuf, burrata, iberijska šunka i svježi bosiljak. Ograničena dostupnost.", price: "Od 17 €" },
          { icon: "package", title: "Dostava na kućnu adresu", desc: "Svježa pizza na vašim vratima za 30 minuta. Min. narudžba 12 €, besplatno iznad 25 €.", price: "Besplatno iznad 25 €" },
        ],
        reviews: [
          { name: "Ivan Horvat", role: "Stalni gost", text: "Najbolja pizza u Zagrebu – to govorim svima. Impasto je savršen, kao u Napulju. Vraćam se svaki tjedan. Samo bih volio da prošire terasu!", rating: 5 },
          { name: "Petra Marić", role: "Food blogerica", text: "Peć na drva mijenja sve. Hrskavi rub, blago pečena sredina, svježi dodaci. Teško pronaći autentičniju pizzu u Hrvatskoj.", rating: 5 },
          { name: "Matej Novak", role: "Voditelj tima", text: "Naručujemo za ručak već 2 godine. Uvijek na vrijeme, uvijek svježe i ukusno. Cijeli tim je oduševljen. Obavezno isprobajte!", rating: 5 },
        ],
        whyUs: [
          { icon: "flame", title: "Peć na drva", desc: "Tradicionalna napolitanska tehnika: kamena peć na 485°C – pizza se peče za 90 sekundi." },
          { icon: "clock", title: "Tijesto 48 sati", desc: "Duga hladna fermentacija stvara lakše probavljivo, hrskavije tijesto." },
          { icon: "leaf", title: "Talijanski sastojci", desc: "Uvezeni San Marzano rajčice, DOC mozzarella, svježi bosiljak – sve iz Italije." },
          { icon: "star", title: "Vegetarijanske opcije", desc: "5 pizza bez mesa na meniju, sa sezonskim povrćem i premium sirevima." },
          { icon: "truck", title: "Dostava kući", desc: "Stižemo za 30 minuta. Naručite online, e-mailom ili telefonom." },
          { icon: "zap", title: "Brza usluga", desc: "Jedete ovdje? Svježe pečena pizza dolazi za stol za 15 minuta." },
        ],
        faq: [
          { q: "Koje su vaše radno vrijeme?", a: "Pon–Čet: 11:00–22:00, Pet–Sub: 11:00–23:00, Ned: 12:00–21:00. Eventualne izmjene za blagdane objavljujemo na Facebooku." },
          { q: "Dostavljate li?", a: "Da! Naručite telefonom ili e-mailom. Dostavljamo za 30 minuta, besplatno iznad 25 €." },
          { q: "Imate li vegetarijanske ili veganske opcije?", a: "Da, 5 vegetarijanskih i 2 veganske pizze. Po zahtjevu možemo i s bezlaktoznim sirom." },
          { q: "Mogu li naručiti unaprijed?", a: "Da, i do 3 dana unaprijed. Za grupne narudžbe (10+ pizza) preporučamo rezervaciju." },
          { q: "Što je napolitanska pizza i zašto je drugačija?", a: "Napolitanska pizza je UNESCO baština. Karakteristike: tanko ručno razvučeno tijesto, debeli prozračni rub (cornicione) i kratko pečenje (90 s) na visokoj temperaturi." },
        ],
        aboutTitle: "Bok, ja sam Gabriele!",
        aboutText: "Naučio sam umijeće pizze u Napulju u trogeneracijskoj pizzeriji, a 2019. otvorio sam Napoli Pizzeriu u Zagrebu. Slijedim ista načela: dobro talijansko brašno (Caputo), duga hladna fermentacija, svježi sastojci i peć na drva. Napoli nije restoran – to je strast.",
        navServices: "Jelovnik",
        navAbout: "O nama",
        navReviews: "Recenzije",
        navFaq: "FAQ",
        navContact: "Kontakt",
        sectionWhyUs: "Zašto Napoli?",
        sectionAbout: "O nama",
        sectionServices: "Naš jelovnik",
        sectionReviews: "Recenzije gostiju",
        sectionFaq: "Često postavljana pitanja",
        sectionContact: "Kontakt & Narudžbe",
        contactFormTitle: "Narudžba ili pitanje",
        contactFormSubmit: "Pošalji poruku",
        contactFormSuccess: "Hvala! Javit ćemo se uskoro.",
        bannerText: "Ovo je primjer web stranice. I vi možete imati ovakvu.",
        bannerCta: "Zatražite ponudu",
      },
      ro: {
        businessName: "Napoli Pizzeria",
        ownerName: "Gabriel Ionescu",
        profession: "Maestru pizzar",
        tagline: "Pizza napolitană autentică, coaptă cu suflet.",
        heroSubtitle: "Aluat întins manual, fermentare 48 ore, cuptor pe lemne – cea mai bună pizza din București. Comandă livrare sau vino la noi!",
        ctaText: "Comandă acum",
        ctaPhone: "Sună-ne",
        phone: "+40 721 345 678",
        email: "gabriel@napolipizzeria.ro",
        address: "București, Calea Victoriei 22",
        mapQuery: "București, Calea Victoriei 22",
        hours: ["Lun–Joi: 11:00–22:00", "Vin–Sâm: 11:00–23:00", "Dum: 12:00–21:00"],
        ratingScore: "4.8",
        ratingCount: "312 recenzii",
        services: [
          { icon: "pizza", title: "Pizze clasice", desc: "Margherita, Diavola, Quattro Stagioni și încă 15 variante – toate din cuptorul pe lemne, gata în 90 de secunde.", price: "De la 35 lei" },
          { icon: "flame", title: "Pizze premium", desc: "Creații sezoniere cu toppinguri premium: trufe negre, burrata, șuncă iberică și busuioc proaspăt. Disponibilitate limitată.", price: "De la 55 lei" },
          { icon: "package", title: "Livrare la domiciliu", desc: "Pizza proaspătă la ușa ta în 30 de minute. Comandă minimă 40 lei, gratuită peste 80 lei.", price: "Gratuită peste 80 lei" },
        ],
        reviews: [
          { name: "Andrei Popescu", role: "Client fidel", text: "Cea mai bună pizza din București – le spun tuturor. Impasto-ul e perfect, ca la Napoli. Vin săptămânal. Aș vrea doar să extindă terasa!", rating: 5 },
          { name: "Maria Ionescu", role: "Food blogger", text: "Cuptorul pe lemne schimbă totul. Blat crocant, miez ușor copt, toppinguri proaspete. Greu de găsit o pizza mai autentică în România.", rating: 5 },
          { name: "Bogdan Stan", role: "Team lead", text: "Comandăm la prânz de 2 ani. Mereu la timp, mereu proaspătă și delicioasă. Toată echipa adoră. Obligatoriu de încercat!", rating: 5 },
        ],
        whyUs: [
          { icon: "flame", title: "Cuptor pe lemne", desc: "Tehnică napolitană tradițională: cuptor de piatră la 485°C – pizza coaptă în 90 de secunde." },
          { icon: "clock", title: "Aluat 48 ore", desc: "Fermentarea lungă la rece creează un aluat mai ușor de digerat, mai crocant." },
          { icon: "leaf", title: "Ingrediente italiene", desc: "Roșii San Marzano importate, mozzarella DOC, busuioc proaspăt – totul din Italia." },
          { icon: "star", title: "Opțiuni vegetariene", desc: "5 pizze fără carne în meniu, cu legume de sezon și brânzeturi premium." },
          { icon: "truck", title: "Livrare acasă", desc: "Ajungem în 30 de minute. Comandă online, prin e-mail sau telefonic." },
          { icon: "zap", title: "Serviciu rapid", desc: "Mănânci la noi? Pizza proaspăt coaptă ajunge la masă în 15 minute." },
        ],
        faq: [
          { q: "Care sunt orele de funcționare?", a: "Lun–Joi: 11:00–22:00, Vin–Sâm: 11:00–23:00, Dum: 12:00–21:00. Orice modificare de sărbători o postăm pe Facebook." },
          { q: "Livrați la domiciliu?", a: "Da! Comandă telefonic sau prin e-mail. Livrăm în 30 de minute, gratuit peste 80 lei." },
          { q: "Aveți opțiuni vegetariene sau vegane?", a: "Da, 5 pizze vegetariene și 2 vegane. La cerere le facem și cu brânză fără lactoză." },
          { q: "Pot comanda în avans?", a: "Da, cu până la 3 zile înainte. Pentru comenzi de grup (10+ pizze) recomandăm rezervarea." },
          { q: "Ce face pizza napolitană diferită?", a: "Pizza napolitană e patrimoniu UNESCO. Caracteristici: blat subțire întins manual, margine groasă și aerată (cornicione) și timp scurt de coacere (90 s) la temperatură mare." },
        ],
        aboutTitle: "Bună, sunt Gabriel!",
        aboutText: "Am învățat arta pizzei la Napoli, la o pizzerie cu tradiție de trei generații, și în 2019 am deschis Napoli Pizzeria în București. Urmez aceleași principii: făină bună italiană (Caputo), fermentare lungă la rece, ingrediente proaspete și, desigur, cuptorul pe lemne. Napoli nu e un restaurant – e o pasiune.",
        navServices: "Meniu",
        navAbout: "Despre noi",
        navReviews: "Recenzii",
        navFaq: "FAQ",
        navContact: "Contact",
        sectionWhyUs: "De ce Napoli?",
        sectionAbout: "Despre noi",
        sectionServices: "Meniul nostru",
        sectionReviews: "Recenzii clienți",
        sectionFaq: "Întrebări frecvente",
        sectionContact: "Contact & Comenzi",
        contactFormTitle: "Comandă sau întrebare",
        contactFormSubmit: "Trimite mesajul",
        contactFormSuccess: "Mulțumim! Te contactăm în curând.",
        bannerText: "Acesta este un site demonstrativ. Poți avea unul la fel.",
        bannerCta: "Solicită ofertă",
      },
    },
  },

  // ─── BŐRÁPOLÁS ──────────────────────────────────────────────────────────────
  {
    slug: "borapalas",
    emoji: "🌿",
    heroImageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1400&q=80",
    galleryLabel: {
      hu: { type: "Bőrápolás", name: "Tiszta Bőr Stúdió" },
      en: { type: "Skin care", name: "Clear Skin Studio" },
      hr: { type: "Njega kože", name: "Čista Koža Studio" },
      ro: { type: "Îngrijire piele", name: "Studio Piele Curată" },
    },
    theme: themes.teal,
    content: {
      hu: {
        businessName: "Tiszta Bőr Stúdió",
        ownerName: "Szabó Virág",
        profession: "Bőrgyógyászati kozmetikus",
        tagline: "Az egészséges bőr a legjobb kozmetikum.",
        heroSubtitle: "Szakmai bőranalízissel kezdünk, majd személyre szabott kezelési tervvel dolgozzuk ki a legtökéletesebb rutint. Ingyenes konzultáció az első látogatáskor.",
        ctaText: "Ingyenes konzultáció",
        ctaPhone: "Foglalj telefonon",
        phone: "+36 30 456 7891",
        email: "virag@tisztabor.hu",
        address: "Budapest, Király utca 38.",
        mapQuery: "Budapest, Király utca 38",
        hours: ["H–P: 10:00–19:00", "Sz: 10:00–16:00", "V: Zárva"],
        ratingScore: "5.0",
        ratingCount: "89 értékelés",
        services: [
          { icon: "droplets", title: "Ingyenes bőranalízis", desc: "Digitális bőranalízissel pontosan meghatározzuk a bőrtípusodat, bőrproblémáidat és a legjobb kezelési rutint – ezzel kezdünk.", price: "Ingyenes" },
          { icon: "sparkles", title: "Mélytisztítás & hidratálás", desc: "Professzionális mélytisztítás, pórusszűkítés, intenzív hidratáló kezelés. 60 perces, minden bőrtípusra ajánlott.", price: "14 000 Ft-tól" },
          { icon: "zap", title: "Bőrmegújító kezelések", desc: "Mikroneedling, kémiai hámlasztás, LED-fényes kezelés és mélyhidratáló oxigénes kezelés – a tökéletes, ragyogó bőrért.", price: "22 000 Ft-tól" },
        ],
        reviews: [
          { name: "Kovács Bori", role: "Ügyvéd", text: "3 hónap alatt teljesen megváltozott a bőröm. Virág pontosan tudta, mire van szükségem – nem adott el felesleges termékeket, csak azt, ami tényleg működik. Életre szóló ügyfél lettem.", rating: 5 },
          { name: "Tóth Zsuzsi", role: "Négygyermekes anyuka", text: "Végre valaki, aki nem csak krémeket ad el, hanem valóban megérti és megmagyarázza a bőröm állapotát. Ez a stúdió egy kincs – ajánlom minden ismerősömnek.", rating: 5 },
          { name: "Fekete Réka", role: "Marketing igazgató", text: "Stresszes munkám ellenére ragyog a bőröm. A rendszeres kezelések és a személyre szabott otthoni rutin csodát tesznek – ezt nem vártam volna ilyen gyorsan.", rating: 5 },
        ],
        whyUs: [
          { icon: "droplets", title: "Ingyenes bőranalízis", desc: "Minden kezelés előtt ingyenes digitális bőranalízis – így pontosan tudjuk, mire van szükséged." },
          { icon: "heart", title: "Személyre szabott", desc: "Nincs két egyforma bőr – minden kezelési tervet az adott bőr igényeihez igazítunk." },
          { icon: "star", title: "Prémium termékek", desc: "Kizárólag dermatológiailag tesztelt, orvosi minőségű termékeket használunk és ajánlunk." },
          { icon: "leaf", title: "Természetes módszerek", desc: "Ahol lehet, természetes és vegán összetevőket részesítünk előnyben, kíméletes technikákkal." },
          { icon: "zap", title: "Modern eszközök", desc: "LED-fény, ultrahang, mikroneedling – a legmodernebb, klinikailag igazolt technológiák." },
          { icon: "clock", title: "Rugalmas foglalás", desc: "Online vagy telefonos időpontfoglalás, este 7-ig. Hétvégi időpontok is elérhetők." },
        ],
        faq: [
          { q: "Szükséges-e előzetes konzultáció?", a: "Igen, minden új ügyfélnek ingyenes bőranalízissel kezdünk. Ez 15–20 percet vesz igénybe, és pontosan megmutatja, milyen kezelésre van szükséged." },
          { q: "Mennyi ideig tart egy kezelés?", a: "Az alapkezelések 45–60 percig tartanak. A megújító kezelések (mikroneedling, kémiai hámlasztás) 75–90 percig." },
          { q: "Mire kell készülni az első látogatáshoz?", a: "Smink nélkül érdemes jönni, vagy hozz arctörlőt. Napsütéses bőr esetén (pl. friss barnulás után) szólj előre." },
          { q: "Mikor láthatók az eredmények?", a: "Legtöbb kezelésnél már az első alkalom után látható javulás. A tartós eredményekhez 3–6 rendszeres kezelést ajánlunk." },
          { q: "Kapható-e ajándékutalvány?", a: "Igen! Bármilyen kezelésre váltható ajándékutalványt érvényes 6 hónapig. Emailben vagy személyesen kérhető." },
        ],
        aboutTitle: "Szia, Virág vagyok!",
        aboutText: "Bőrgyógyászati kozmetikusként dolgozom 9 éve, és abban hiszek, hogy az egészséges bőr nem szerencse kérdése – hanem a megfelelő rutiné. Nem árulok sablonos kezeléseket: minden ügyfelem bőrét egyedileg vizsgálom meg, és arra a problémára adok megoldást, ami tényleg létezik. Célom nem csupán szép bőrt adni, hanem megérteted veled, hogyan tartsd meg.",
        navServices: "Kezelések",
        navAbout: "Rólam",
        navReviews: "Vélemények",
        navFaq: "GYIK",
        navContact: "Foglalás",
        sectionWhyUs: "Miért minket válassz?",
        sectionAbout: "Rólam",
        sectionServices: "Kezeléseink",
        sectionReviews: "Ügyfélvélemények",
        sectionFaq: "Gyakori kérdések",
        sectionContact: "Időpontfoglalás",
        contactFormTitle: "Foglalj időpontot",
        contactFormSubmit: "Időpont kérése",
        contactFormSuccess: "Köszönjük! Hamarosan visszajelzünk.",
        bannerText: "Ez egy minta weboldal. Ilyen weboldalad is lehet.",
        bannerCta: "Kérj ajánlatot",
      },
      en: {
        businessName: "Clear Skin Studio",
        ownerName: "Violet Shaw",
        profession: "Skin Care Specialist",
        tagline: "Healthy skin is the best cosmetic.",
        heroSubtitle: "We start with a professional skin analysis, then build a personalised treatment plan. Free consultation on your first visit.",
        ctaText: "Free consultation",
        ctaPhone: "Book by phone",
        phone: "+44 7912 456789",
        email: "violet@clearskin.co.uk",
        address: "38 King Street, Edinburgh",
        mapQuery: "38 King Street, Edinburgh, UK",
        hours: ["Mon–Fri: 10:00–19:00", "Sat: 10:00–16:00", "Sun: Closed"],
        ratingScore: "5.0",
        ratingCount: "89 reviews",
        services: [
          { icon: "droplets", title: "Free skin analysis", desc: "Digital skin analysis to identify your skin type, concerns and the best treatment routine – this is always where we start.", price: "Free" },
          { icon: "sparkles", title: "Deep cleanse & hydration", desc: "Professional deep cleansing, pore minimising, intense hydration treatment. 60 minutes, suitable for all skin types.", price: "From £85" },
          { icon: "zap", title: "Skin renewal treatments", desc: "Microneedling, chemical peels, LED light therapy and deep oxygen treatment – for flawless, glowing skin.", price: "From £130" },
        ],
        reviews: [
          { name: "Brenda Collins", role: "Lawyer", text: "My skin completely transformed in 3 months. Violet knew exactly what I needed – no unnecessary products, only what actually works. I'm a client for life.", rating: 5 },
          { name: "Susan Thomas", role: "Mother of four", text: "Finally someone who not only sells creams but truly understands and explains your skin. This studio is a gem – I recommend it to everyone.", rating: 5 },
          { name: "Rebecca Ford", role: "Marketing director", text: "Despite my stressful job, my skin glows. The regular treatments and personalised home routine work wonders – I didn't expect results this fast.", rating: 5 },
        ],
        whyUs: [
          { icon: "droplets", title: "Free skin analysis", desc: "Free digital skin analysis before every treatment – so we know exactly what you need." },
          { icon: "heart", title: "Personalised", desc: "No two skins are alike – every treatment plan is tailored to your specific skin's needs." },
          { icon: "star", title: "Premium products", desc: "We use and recommend only dermatologically tested, medical-grade products." },
          { icon: "leaf", title: "Natural methods", desc: "Where possible, we prefer natural and vegan ingredients, with gentle techniques." },
          { icon: "zap", title: "Modern devices", desc: "LED light, ultrasound, microneedling – the latest clinically proven technologies." },
          { icon: "clock", title: "Flexible booking", desc: "Online or phone booking, until 7pm. Weekend appointments also available." },
        ],
        faq: [
          { q: "Is a consultation required?", a: "Yes, every new client starts with a free skin analysis. It takes 15–20 minutes and shows precisely what treatment you need." },
          { q: "How long does a treatment take?", a: "Core treatments are 45–60 minutes. Renewal treatments (microneedling, peels) are 75–90 minutes." },
          { q: "How should I prepare for my first visit?", a: "Best to arrive without makeup, or bring a facial wipe. If your skin is freshly tanned (e.g. sunburn), let us know in advance." },
          { q: "When will I see results?", a: "Most treatments show visible improvement after the first session. For lasting results we recommend 3–6 regular treatments." },
          { q: "Are gift vouchers available?", a: "Yes! Gift vouchers redeemable against any treatment, valid for 6 months. Request by email or in person." },
        ],
        aboutTitle: "Hi, I'm Violet!",
        aboutText: "I've been a skin care specialist for 9 years, and I believe healthy skin isn't luck – it's the right routine. I don't sell template treatments: I assess every client's skin individually and address what actually exists. My goal isn't just beautiful skin – it's helping you understand how to keep it.",
        navServices: "Treatments",
        navAbout: "About",
        navReviews: "Reviews",
        navFaq: "FAQ",
        navContact: "Book",
        sectionWhyUs: "Why choose us?",
        sectionAbout: "About me",
        sectionServices: "Our treatments",
        sectionReviews: "Client reviews",
        sectionFaq: "Frequently asked questions",
        sectionContact: "Book an appointment",
        contactFormTitle: "Book an appointment",
        contactFormSubmit: "Request appointment",
        contactFormSuccess: "Thank you! We'll be in touch soon.",
        bannerText: "This is a sample website. You could have one just like it.",
        bannerCta: "Get a quote",
      },
      hr: {
        businessName: "Čista Koža Studio",
        ownerName: "Viola Šarić",
        profession: "Specijalistica njege kože",
        tagline: "Zdrava koža je najbolji kozmetik.",
        heroSubtitle: "Počinjemo stručnom analizom kože, zatim gradimo personalizirani plan tretmana. Besplatna konzultacija pri prvom posjetu.",
        ctaText: "Besplatna konzultacija",
        ctaPhone: "Rezerviraj telefonom",
        phone: "+385 91 456 7891",
        email: "viola@cistakoza.hr",
        address: "Split, Marmontova 38",
        mapQuery: "Split, Marmontova 38",
        hours: ["Pon–Pet: 10:00–19:00", "Sub: 10:00–16:00", "Ned: Zatvoreno"],
        ratingScore: "5.0",
        ratingCount: "89 recenzija",
        services: [
          { icon: "droplets", title: "Besplatna analiza kože", desc: "Digitalna analiza kože kako bismo utvrdili vaš tip kože, probleme i najbolji rutinski plan – uvijek s tim počinjemo.", price: "Besplatno" },
          { icon: "sparkles", title: "Duboko čišćenje & hidratacija", desc: "Profesionalno duboko čišćenje, smanjivanje pora, intenzivni hidratantni tretman. 60 minuta, za sve tipove kože.", price: "Od 65 €" },
          { icon: "zap", title: "Tretmani obnove kože", desc: "Mikroneedling, kemijski piling, LED svjetlosna terapija i duboki kisikanski tretman – za savršenu, sjajnu kožu.", price: "Od 100 €" },
        ],
        reviews: [
          { name: "Branka Kovač", role: "Odvjetnica", text: "Koža mi se potpuno promijenila za 3 mjeseca. Viola je znala točno što mi treba – bez nepotrebnih proizvoda, samo ono što stvarno funkcionira. Postala sam klijentica za cijeli život.", rating: 5 },
          { name: "Suzana Jurić", role: "Majka četvero djece", text: "Konačno netko tko ne prodaje samo kreme već zaista razumije i objašnjava stanje vaše kože. Ovaj studio je dragulj – preporučujem svima.", rating: 5 },
          { name: "Rebeka Novak", role: "Marketing direktorica", text: "Usprkos stresnom poslu, koža mi sija. Redoviti tretmani i personalizirana rutina za kući čude – nisam očekivala rezultate tako brzo.", rating: 5 },
        ],
        whyUs: [
          { icon: "droplets", title: "Besplatna analiza kože", desc: "Besplatna digitalna analiza kože prije svakog tretmana – da znamo točno što vam treba." },
          { icon: "heart", title: "Personalizirano", desc: "Ne postoje dvije iste kože – svaki plan tretmana prilagođen je specifičnim potrebama vaše kože." },
          { icon: "star", title: "Premium proizvodi", desc: "Koristimo i preporučamo samo dermatološki testirane, medicinski kvalitetne proizvode." },
          { icon: "leaf", title: "Prirodne metode", desc: "Gdje je moguće, preferiramo prirodne i veganske sastojke, s nježnim tehnikama." },
          { icon: "zap", title: "Moderni uređaji", desc: "LED svjetlo, ultrazvuk, mikroneedling – najnovije klinički dokazane tehnologije." },
          { icon: "clock", title: "Fleksibilno rezerviranje", desc: "Online ili telefonska rezervacija, do 19 sati. Dostupni i vikend termini." },
        ],
        faq: [
          { q: "Je li potrebna konzultacija?", a: "Da, svaki novi klijent počinje besplatnom analizom kože. Traje 15–20 minuta i točno pokazuje koji tretman vam treba." },
          { q: "Koliko dugo traje tretman?", a: "Osnovni tretmani traju 45–60 minuta. Tretmani obnove (mikroneedling, pilizi) traju 75–90 minuta." },
          { q: "Kako se pripremiti za prvi posjet?", a: "Najbolje doći bez šminke ili ponijeti maramice za lice. Ako je koža svježe preplanula, obavijestite nas unaprijed." },
          { q: "Kada će se vidjeti rezultati?", a: "Većina tretmana pokazuje vidljivo poboljšanje već nakon prve sesije. Za trajne rezultate preporučujemo 3–6 redovitih tretmana." },
          { q: "Dostupni li poklon bonovi?", a: "Da! Poklon bonovi zamjenjivi za bilo koji tretman, vrijede 6 mjeseci. Zatražite e-mailom ili osobno." },
        ],
        aboutTitle: "Bok, ja sam Viola!",
        aboutText: "Radim kao specijalistica njege kože 9 godina i vjerujem da zdrava koža nije stvar sreće – već prave rutine. Ne prodajem standardne tretmane: procjenjujem kožu svakog klijenta individualno i rješavam ono što stvarno postoji. Moj cilj nije samo lijepa koža – nego razumjeti kako je održati.",
        navServices: "Tretmani",
        navAbout: "O meni",
        navReviews: "Recenzije",
        navFaq: "FAQ",
        navContact: "Rezervacija",
        sectionWhyUs: "Zašto nas odabrati?",
        sectionAbout: "O meni",
        sectionServices: "Naši tretmani",
        sectionReviews: "Recenzije klijenata",
        sectionFaq: "Često postavljana pitanja",
        sectionContact: "Rezervirajte termin",
        contactFormTitle: "Rezervirajte termin",
        contactFormSubmit: "Zatraži termin",
        contactFormSuccess: "Hvala! Javit ćemo se uskoro.",
        bannerText: "Ovo je primjer web stranice. I vi možete imati ovakvu.",
        bannerCta: "Zatražite ponudu",
      },
      ro: {
        businessName: "Studio Piele Curată",
        ownerName: "Violeta Sandu",
        profession: "Specialist îngrijire piele",
        tagline: "Pielea sănătoasă este cel mai bun cosmetic.",
        heroSubtitle: "Începem cu o analiză profesională a pielii, apoi construim un plan de tratament personalizat. Consultație gratuită la prima vizită.",
        ctaText: "Consultație gratuită",
        ctaPhone: "Rezervă telefonic",
        phone: "+40 745 456 789",
        email: "violeta@pielesanatas.ro",
        address: "Timișoara, Bd. Republicii 38",
        mapQuery: "Timișoara, Bd. Republicii 38",
        hours: ["Lun–Vin: 10:00–19:00", "Sâm: 10:00–16:00", "Dum: Închis"],
        ratingScore: "5.0",
        ratingCount: "89 recenzii",
        services: [
          { icon: "droplets", title: "Analiză piele gratuită", desc: "Analiză digitală a pielii pentru a identifica tipul, problemele și cea mai bună rutină de tratament – întotdeauna cu asta începem.", price: "Gratuită" },
          { icon: "sparkles", title: "Curățare profundă & hidratare", desc: "Curățare profesională profundă, minimizarea porilor, tratament intens de hidratare. 60 minute, pentru toate tipurile de piele.", price: "De la 200 lei" },
          { icon: "zap", title: "Tratamente de reînnoire", desc: "Microneedling, peelinguri chimice, terapie LED și tratament oxigenat profund – pentru o piele perfectă, strălucitoare.", price: "De la 350 lei" },
        ],
        reviews: [
          { name: "Brândușa Popa", role: "Avocat", text: "Pielea mea s-a transformat complet în 3 luni. Violeta a știut exact ce am nevoie – fără produse inutile, doar ce funcționează cu adevărat. Am devenit clientă pe viață.", rating: 5 },
          { name: "Suzana Ionescu", role: "Mamă a patru copii", text: "În sfârșit cineva care nu vinde doar creme ci înțelege și explică starea pielii tale. Acest studio e o comoară – îl recomand tuturor.", rating: 5 },
          { name: "Rebeca Stan", role: "Director marketing", text: "În ciuda jobului stresant, pielea mea strălucește. Tratamentele regulate și rutina personalizată acasă fac minuni – nu mă așteptam la rezultate atât de rapide.", rating: 5 },
        ],
        whyUs: [
          { icon: "droplets", title: "Analiză piele gratuită", desc: "Analiză digitală gratuită înainte de fiecare tratament – astfel știm exact ce ai nevoie." },
          { icon: "heart", title: "Personalizat", desc: "Nu există două pieli la fel – fiecare plan de tratament e adaptat nevoilor specifice ale pielii tale." },
          { icon: "star", title: "Produse premium", desc: "Folosim și recomandăm doar produse testate dermatologic, de calitate medicală." },
          { icon: "leaf", title: "Metode naturale", desc: "Acolo unde e posibil, preferăm ingrediente naturale și vegane, cu tehnici blânde." },
          { icon: "zap", title: "Echipamente moderne", desc: "Lumină LED, ultrasunete, microneedling – cele mai noi tehnologii clinic dovedite." },
          { icon: "clock", title: "Programare flexibilă", desc: "Programare online sau telefonic, până la ora 19. Disponibile și programări de weekend." },
        ],
        faq: [
          { q: "Este necesară o consultație?", a: "Da, fiecare client nou începe cu o analiză gratuită a pielii. Durează 15–20 minute și arată exact ce tratament ai nevoie." },
          { q: "Cât durează un tratament?", a: "Tratamentele de bază durează 45–60 minute. Tratamentele de reînnoire (microneedling, peelinguri) durează 75–90 minute." },
          { q: "Cum mă pregătesc pentru prima vizită?", a: "E mai bine să vii fără machiaj sau să aduci șervețele demachiante. Dacă pielea ta e recent bronzată, anunță-ne în avans." },
          { q: "Când voi vedea rezultate?", a: "Majoritatea tratamentelor arată îmbunătățiri vizibile după prima sesiune. Pentru rezultate de durată recomandăm 3–6 tratamente regulate." },
          { q: "Sunt disponibile vouchere cadou?", a: "Da! Vouchere cadou valorificabile pentru orice tratament, valabile 6 luni. Solicită prin e-mail sau personal." },
        ],
        aboutTitle: "Bună, sunt Violeta!",
        aboutText: "Sunt specialist în îngrijirea pielii de 9 ani și cred că pielea sănătoasă nu e noroc – ci rutina potrivită. Nu vând tratamente standard: evaluez pielea fiecărui client individual și rezolv ce există cu adevărat. Scopul meu nu e doar piele frumoasă – ci să înțelegi cum să o menții.",
        navServices: "Tratamente",
        navAbout: "Despre mine",
        navReviews: "Recenzii",
        navFaq: "FAQ",
        navContact: "Programare",
        sectionWhyUs: "De ce să ne alegi?",
        sectionAbout: "Despre mine",
        sectionServices: "Tratamentele noastre",
        sectionReviews: "Recenzii clienți",
        sectionFaq: "Întrebări frecvente",
        sectionContact: "Programează-te",
        contactFormTitle: "Programează-te",
        contactFormSubmit: "Solicită programare",
        contactFormSuccess: "Mulțumim! Te contactăm în curând.",
        bannerText: "Acesta este un site demonstrativ. Poți avea unul la fel.",
        bannerCta: "Solicită ofertă",
      },
    },
  },

  // ─── INGATLAN ───────────────────────────────────────────────────────────────
  {
    slug: "ingatlan",
    emoji: "🏠",
    heroImageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1400&q=80",
    galleryLabel: {
      hu: { type: "Ingatlanközvetítő", name: "Molnár Ingatlan" },
      en: { type: "Real estate agent", name: "Mason Realty" },
      hr: { type: "Agent za nekretnine", name: "Milić Nekretnine" },
      ro: { type: "Agent imobiliar", name: "Marin Imobiliare" },
    },
    theme: themes.blue,
    content: {
      hu: {
        businessName: "Molnár Ingatlan",
        ownerName: "Molnár Péter",
        profession: "Ingatlanközvetítő szakértő",
        tagline: "A legjobb ingatlanüzlet, ami valaha volt.",
        heroSubtitle: "12 év tapasztalat, 400+ lezárt üzlet Budapesten. Vásárolnál, eladnál vagy befektetnél? Ingyenes konzultációval kezdünk.",
        ctaText: "Ingyenes konzultáció",
        ctaPhone: "Hívj most",
        phone: "+36 30 567 8901",
        email: "peter@molnaringatlan.hu",
        address: "Budapest, Andrássy út 55. (5. em.)",
        mapQuery: "Budapest, Andrássy út 55",
        hours: ["H–P: 9:00–18:00", "Sz: Előzetes egyeztetéssel", "V: Zárva"],
        ratingScore: "4.9",
        ratingCount: "214 értékelés",
        services: [
          { icon: "home", title: "Ingatlan eladás", desc: "Professzionális értékbecslés, HD fotózás, célzott marketing és teljes körű ügyintézés a szerződéskötésig. A mi célunk a legjobb ár elérése.", price: "Sikerdíjas" },
          { icon: "key", title: "Ingatlan vásárlás", desc: "Segítünk megtalálni az igényeidhez és büdzséjéhez illő ingatlant. Tárgyalunk helyetted, ellenőrzünk minden dokumentumot, végigkísérünk.", price: "Ingyenes vásárlónak" },
          { icon: "building", title: "Befektetési tanácsadás", desc: "Melyek a legjobb befektetési célpontok ma? Piacelemzés, hozamszámítás, kockázatértékelés és konkrét javaslatok.", price: "Ingyenes konzultáció" },
        ],
        reviews: [
          { name: "Farkas Judit", role: "Eladó, XIV. kerület", text: "Péterrel 3 héten belül eladtuk a lakást – 8%-kal a kért ár felett! Profi marketing, gyors reagálás, precíz ügyintézés. Mindenkinek ajánlom, aki el akar adni.", rating: 5 },
          { name: "Szilágyi Tamás", role: "Első lakásvásárló", text: "Első lakásvásárlóként tele voltam kérdésekkel. Péter mindent megmagyarázott, végig ott volt és megtalálta a tökéletes lakást a büdzsémen belül. Hihetetlenül hálás vagyok.", rating: 5 },
          { name: "Bíró Katalin", role: "Ingatlanbefektető", text: "2 befektetési ingatlant vettem Péterrel az elmúlt évben. Mindkétszer kiváló piaci ismerettel segített, és mindkét üzlet profitábilis volt. Megbízható és kompetens.", rating: 5 },
        ],
        whyUs: [
          { icon: "star", title: "12 év tapasztalat", desc: "400+ lezárt üzlet Budapesten és agglomerációjában – teljes piaci átlátás." },
          { icon: "home", title: "Ingyenes értékbecslés", desc: "Az ingatlanod valós piaci értékét megmondjuk – ingyen, kötelezettség nélkül." },
          { icon: "zap", title: "Gyors eladás", desc: "Átlagos eladási időnk 21 nap – a piaci átlag 90 naphoz képest." },
          { icon: "shield", title: "Teljes körű ügyintézés", desc: "A hirdetéstől a kulcsátadásig mindent intézünk – neked csak jóváhagyni kell." },
          { icon: "users", title: "Vevői érdekképviselet", desc: "Vásárlóknak ingyenes a szolgáltatásunk – az érdekeidet képviseljük a tárgyaláson." },
          { icon: "bar-chart", title: "Piacelemzés", desc: "Rendszeres piacelemzéssel a legjobb időpontban adunk el vagy vásárolunk." },
        ],
        faq: [
          { q: "Mibe kerül az ingatlan értékbecslés?", a: "Teljesen ingyenes és kötelezettségmentes. Felmérjük az ingatlant, megnézzük a piaci összehasonlítókat, és reális árat javaslunk." },
          { q: "Mennyi ideig tart egy ingatlan eladása?", a: "Átlagosan 21 napot vesz igénybe a hirdetéstől az aláírásig. Ez a piaci átlag töredéke – köszönhetően a célzott marketingnek." },
          { q: "Milyen dokumentumok kellenek az eladáshoz?", a: "Tulajdoni lap, alaprajz (ha van), energetikai tanúsítvány. Segítünk beszerezni, amit nem találsz." },
          { q: "Van-e jutalék a vásárlók számára?", a: "Nem, a vásárlók számára a szolgáltatás ingyenes. Az eladó fizet sikerdíjat, csak eredményes üzletkötés esetén." },
          { q: "Milyen területen dolgoztok?", a: "Elsősorban Budapest és az agglomeráció (30 km-es körzet), de egyéni egyeztetéssel vidéki ingatlanokat is vállalunk." },
        ],
        aboutTitle: "Szia, Péter vagyok!",
        aboutText: "12 éve vagyok ingatlanközvetítő Budapesten, és 400+ sikeres üzletet zártam le. Nem egy irodát képviselek – az én érdekem és a tiéd ugyanaz: a legjobb üzlet. Nyíltan kommunikálok a reális árakról, a piaci helyzetről és a kockázatokról. Nálam nincs meglepetés – csak eredmény.",
        navServices: "Szolgáltatások",
        navAbout: "Rólam",
        navReviews: "Vélemények",
        navFaq: "GYIK",
        navContact: "Kapcsolat",
        sectionWhyUs: "Miért Molnár Ingatlan?",
        sectionAbout: "Rólam",
        sectionServices: "Szolgáltatásaim",
        sectionReviews: "Ügyfélvélemények",
        sectionFaq: "Gyakori kérdések",
        sectionContact: "Kapcsolat & Konzultáció",
        contactFormTitle: "Ingyenes konzultáció kérése",
        contactFormSubmit: "Konzultáció kérése",
        contactFormSuccess: "Köszönjük! Hamarosan visszajelzünk.",
        bannerText: "Ez egy minta weboldal. Ilyen weboldalad is lehet.",
        bannerCta: "Kérj ajánlatot",
      },
      en: {
        businessName: "Mason Realty",
        ownerName: "Peter Mason",
        profession: "Real Estate Agent & Consultant",
        tagline: "The best property deal you'll ever make.",
        heroSubtitle: "12 years experience, 400+ deals closed in London. Buying, selling or investing? We start with a free consultation.",
        ctaText: "Free consultation",
        ctaPhone: "Call now",
        phone: "+44 7900 567890",
        email: "peter@masonrealty.co.uk",
        address: "55 Park Lane, 5th Floor, London",
        mapQuery: "55 Park Lane, London, UK",
        hours: ["Mon–Fri: 9:00–18:00", "Sat: By appointment", "Sun: Closed"],
        ratingScore: "4.9",
        ratingCount: "214 reviews",
        services: [
          { icon: "home", title: "Property sales", desc: "Professional valuation, HD photography, targeted marketing and full management to exchange. Our goal is the best price.", price: "Commission-based" },
          { icon: "key", title: "Property buying", desc: "We help you find the right property for your needs and budget. We negotiate, check every document and guide you through.", price: "Free for buyers" },
          { icon: "building", title: "Investment consulting", desc: "What are the best investment targets today? Market analysis, yield calculations, risk assessment and concrete recommendations.", price: "Free consultation" },
        ],
        reviews: [
          { name: "Judith Parker", role: "Seller, Kensington", text: "We sold our flat in 3 weeks with Peter – 8% above asking price! Professional marketing, fast responses, precise management. I recommend him to everyone selling.", rating: 5 },
          { name: "Thomas Silva", role: "First-time buyer", text: "As a first-time buyer I had so many questions. Peter explained everything, was there throughout and found the perfect flat within my budget. I'm incredibly grateful.", rating: 5 },
          { name: "Katherine Brown", role: "Property investor", text: "I bought 2 investment properties with Peter in the past year. Both times he helped with excellent market knowledge and both deals were profitable. Reliable and competent.", rating: 5 },
        ],
        whyUs: [
          { icon: "star", title: "12 years experience", desc: "400+ closed deals in London and surroundings – complete market overview." },
          { icon: "home", title: "Free valuation", desc: "We'll tell you your property's real market value – free, no obligation." },
          { icon: "zap", title: "Fast sales", desc: "Our average sale time is 21 days – compared to a market average of 90 days." },
          { icon: "shield", title: "Full management", desc: "From listing to key handover, we handle everything – you just need to approve." },
          { icon: "users", title: "Buyer advocacy", desc: "Our service is free for buyers – we represent your interests in negotiation." },
          { icon: "bar-chart", title: "Market analysis", desc: "Regular market analysis ensures we sell or buy at exactly the right time." },
        ],
        faq: [
          { q: "How much does a valuation cost?", a: "Completely free and with no obligation. We survey the property, check market comparables and suggest a realistic price." },
          { q: "How long does selling a property take?", a: "On average 21 days from listing to exchange. That's a fraction of the market average, thanks to targeted marketing." },
          { q: "What documents are needed to sell?", a: "Title deeds, floor plan (if available), Energy Performance Certificate. We'll help you get anything you can't find." },
          { q: "Is there a fee for buyers?", a: "No, our service is free for buyers. The seller pays a success fee, only on a successful transaction." },
          { q: "What areas do you cover?", a: "Primarily London and within 20 miles. For properties further afield, we can discuss on a case-by-case basis." },
        ],
        aboutTitle: "Hi, I'm Peter!",
        aboutText: "I've been a real estate agent in London for 12 years and closed 400+ successful deals. I don't represent an office – my interest and yours are the same: the best deal. I communicate openly about realistic prices, market conditions and risks. No surprises with me – just results.",
        navServices: "Services",
        navAbout: "About",
        navReviews: "Reviews",
        navFaq: "FAQ",
        navContact: "Contact",
        sectionWhyUs: "Why Mason Realty?",
        sectionAbout: "About me",
        sectionServices: "My services",
        sectionReviews: "Client reviews",
        sectionFaq: "Frequently asked questions",
        sectionContact: "Contact & Consultation",
        contactFormTitle: "Request a free consultation",
        contactFormSubmit: "Request consultation",
        contactFormSuccess: "Thank you! We'll be in touch soon.",
        bannerText: "This is a sample website. You could have one just like it.",
        bannerCta: "Get a quote",
      },
      hr: {
        businessName: "Milić Nekretnine",
        ownerName: "Petar Milić",
        profession: "Agent za nekretnine i savjetnik",
        tagline: "Najbitniji posao s nekretninama koji ćete ikada napraviti.",
        heroSubtitle: "12 godina iskustva, 400+ sklopljenih poslova u Zagrebu. Kupujete, prodajete ili investirate? Počinjemo besplatnom konzultacijom.",
        ctaText: "Besplatna konzultacija",
        ctaPhone: "Nazovite odmah",
        phone: "+385 91 567 8901",
        email: "petar@milic-nekretnine.hr",
        address: "Zagreb, Ilica 55, 5. kat",
        mapQuery: "Zagreb, Ilica 55",
        hours: ["Pon–Pet: 9:00–18:00", "Sub: Uz dogovor", "Ned: Zatvoreno"],
        ratingScore: "4.9",
        ratingCount: "214 recenzija",
        services: [
          { icon: "home", title: "Prodaja nekretnina", desc: "Profesionalna procjena vrijednosti, HD fotografiranje, ciljani marketing i potpuna administracija do potpisa. Naš cilj je postizanje najbolje cijene.", price: "Provizija na uspjeh" },
          { icon: "key", title: "Kupnja nekretnina", desc: "Pomažemo vam pronaći nekretninu koja odgovara vašim potrebama i budžetu. Pregovaramo, provjeravamo sve dokumente i vodimo vas.", price: "Besplatno za kupce" },
          { icon: "building", title: "Investicijsko savjetovanje", desc: "Koji su danas najbolji investicijski ciljevi? Analiza tržišta, izračun prinosa, procjena rizika i konkretne preporuke.", price: "Besplatna konzultacija" },
        ],
        reviews: [
          { name: "Judita Kovač", role: "Prodavačica, Gornji grad", text: "S Petrom smo prodali stan za 3 tjedna – 8% iznad tražene cijene! Profesionalni marketing, brze reakcije, precizna administracija. Preporučujem svima.", rating: 5 },
          { name: "Tomislav Jurić", role: "Kupac prvog stana", text: "Kao kupac po prvi put imao sam puno pitanja. Petar je sve objasnio, bio je tu kroz cijeli proces i pronašao savršen stan unutar budžeta. Iznimno zahvalan.", rating: 5 },
          { name: "Katarina Horvat", role: "Investitorica nekretnina", text: "Kupio sam 2 investicijske nekretnine s Petrom u protekloj godini. Oba puta pomogao je s odličnim poznavanjem tržišta i oba posla bila su isplativa.", rating: 5 },
        ],
        whyUs: [
          { icon: "star", title: "12 godina iskustva", desc: "400+ sklopljenih poslova u Zagrebu i okolici – potpuni pregled tržišta." },
          { icon: "home", title: "Besplatna procjena", desc: "Reći ćemo vam pravu tržišnu vrijednost vaše nekretnine – besplatno, bez obveze." },
          { icon: "zap", title: "Brza prodaja", desc: "Naše prosječno vrijeme prodaje je 21 dan – u usporedbi s tržišnim prosjekom od 90 dana." },
          { icon: "shield", title: "Potpuna administracija", desc: "Od oglašavanja do primopredaje ključeva vodimo sve – vi samo trebate odobriti." },
          { icon: "users", title: "Zastupanje kupaca", desc: "Usluga je besplatna za kupce – zastupamo vaše interese u pregovorima." },
          { icon: "bar-chart", title: "Analiza tržišta", desc: "Redovita analiza tržišta osigurava da prodajemo ili kupujemo u pravo vrijeme." },
        ],
        faq: [
          { q: "Koliko košta procjena nekretnine?", a: "Potpuno besplatno i bez obveze. Obiđemo nekretninu, provjerimo tržišne usporedbe i predložimo realnu cijenu." },
          { q: "Koliko dugo traje prodaja nekretnine?", a: "Prosječno 21 dan od oglašavanja do potpisa. To je samo dio tržišnog prosjeka zahvaljujući ciljanom marketingu." },
          { q: "Koji dokumenti su potrebni za prodaju?", a: "Vlasnički list, tlocrt (ako postoji), energetski certifikat. Pomoći ćemo vam pribaviti ono što ne možete pronaći." },
          { q: "Plaćaju li kupci proviziju?", a: "Ne, usluga je besplatna za kupce. Prodavač plaća proviziju za uspjeh, samo u slučaju uspješne transakcije." },
          { q: "Koje područje pokrivate?", a: "Prvenstveno Zagreb i u polumjeru 30 km. Za nekretnine dalje možemo dogovoriti individualno." },
        ],
        aboutTitle: "Bok, ja sam Petar!",
        aboutText: "Radim kao agent za nekretnine u Zagrebu 12 godina i sklopio sam 400+ uspješnih poslova. Ne zastupam ured – moj interes i vaš su isti: najbitniji posao. Otvoreno komuniciram o realnim cijenama, stanju tržišta i rizicima. Kod mene nema iznenađenja – samo rezultati.",
        navServices: "Usluge",
        navAbout: "O meni",
        navReviews: "Recenzije",
        navFaq: "FAQ",
        navContact: "Kontakt",
        sectionWhyUs: "Zašto Milić Nekretnine?",
        sectionAbout: "O meni",
        sectionServices: "Moje usluge",
        sectionReviews: "Recenzije klijenata",
        sectionFaq: "Često postavljana pitanja",
        sectionContact: "Kontakt & Konzultacija",
        contactFormTitle: "Zatražite besplatnu konzultaciju",
        contactFormSubmit: "Zatraži konzultaciju",
        contactFormSuccess: "Hvala! Javit ćemo se uskoro.",
        bannerText: "Ovo je primjer web stranice. I vi možete imati ovakvu.",
        bannerCta: "Zatražite ponudu",
      },
      ro: {
        businessName: "Marin Imobiliare",
        ownerName: "Petru Marin",
        profession: "Agent imobiliar & consultant",
        tagline: "Cea mai bună tranzacție imobiliară pe care o vei face.",
        heroSubtitle: "12 ani de experiență, 400+ tranzacții finalizate în București. Cumperi, vinzi sau investești? Începem cu o consultație gratuită.",
        ctaText: "Consultație gratuită",
        ctaPhone: "Sună acum",
        phone: "+40 756 567 890",
        email: "petru@marinimobiliare.ro",
        address: "București, Calea Victoriei 55, et. 5",
        mapQuery: "București, Calea Victoriei 55",
        hours: ["Lun–Vin: 9:00–18:00", "Sâm: Cu programare", "Dum: Închis"],
        ratingScore: "4.9",
        ratingCount: "214 recenzii",
        services: [
          { icon: "home", title: "Vânzare proprietăți", desc: "Evaluare profesională, fotografiere HD, marketing targetat și administrare completă până la semnătură. Scopul nostru este cel mai bun preț.", price: "Comision la succes" },
          { icon: "key", title: "Cumpărare proprietăți", desc: "Te ajutăm să găsești proprietatea potrivită pentru nevoile și bugetul tău. Negociem, verificăm fiecare document și te însoțim.", price: "Gratuit pentru cumpărători" },
          { icon: "building", title: "Consultanță investiții", desc: "Care sunt cele mai bune ținte de investiție astăzi? Analiză de piață, calcul randament, evaluare riscuri și recomandări concrete.", price: "Consultație gratuită" },
        ],
        reviews: [
          { name: "Iudita Popa", role: "Vânzătoare, Floreasca", text: "Am vândut apartamentul în 3 săptămâni cu Petru – cu 8% peste prețul cerut! Marketing profesional, răspunsuri rapide, administrare precisă. Îl recomand tuturor.", rating: 5 },
          { name: "Teodor Ionescu", role: "Prim cumpărător", text: "Ca prim cumpărător aveam multe întrebări. Petru a explicat totul, a fost prezent pe tot parcursul și a găsit apartamentul perfect în bugetul meu. Îi sunt extrem de recunoscător.", rating: 5 },
          { name: "Cătălina Rusu", role: "Investitoare imobiliară", text: "Am cumpărat 2 proprietăți de investiție cu Petru în ultimul an. De ambele ori m-a ajutat cu cunoștințe excelente de piață și ambele tranzacții au fost profitabile.", rating: 5 },
        ],
        whyUs: [
          { icon: "star", title: "12 ani de experiență", desc: "400+ tranzacții finalizate în București și împrejurimi – viziune completă asupra pieței." },
          { icon: "home", title: "Evaluare gratuită", desc: "Îți spunem valoarea reală de piață a proprietății – gratuit, fără obligații." },
          { icon: "zap", title: "Vânzare rapidă", desc: "Timpul mediu de vânzare: 21 zile – față de media pieței de 90 zile." },
          { icon: "shield", title: "Administrare completă", desc: "De la listare la predarea cheilor, noi gestionăm totul – tu doar aprobi." },
          { icon: "users", title: "Reprezentare cumpărători", desc: "Serviciul este gratuit pentru cumpărători – reprezentăm interesele tale în negocieri." },
          { icon: "bar-chart", title: "Analiză de piață", desc: "Analiză regulată de piață pentru a vinde sau cumpăra la momentul potrivit." },
        ],
        faq: [
          { q: "Cât costă evaluarea proprietății?", a: "Complet gratuit și fără obligații. Vizităm proprietatea, verificăm comparabile de piață și sugerăm un preț realist." },
          { q: "Cât durează vânzarea unei proprietăți?", a: "În medie 21 zile de la listare la semnătură. E o fracțiune din media pieței, datorită marketingului targetat." },
          { q: "Ce documente sunt necesare pentru vânzare?", a: "Extras de carte funciară, plan cadastral, certificat energetic. Te ajutăm să obții ce nu găsești." },
          { q: "Plătesc cumpărătorii comision?", a: "Nu, serviciul este gratuit pentru cumpărători. Vânzătorul plătește un onorariu de succes, doar la tranzacție finalizată." },
          { q: "Ce zone acoperiți?", a: "În principal București și în raza de 30 km. Pentru proprietăți mai departe, putem discuta individual." },
        ],
        aboutTitle: "Bună, sunt Petru!",
        aboutText: "Sunt agent imobiliar în București de 12 ani și am finalizat 400+ tranzacții de succes. Nu reprezint un birou – interesul meu și al tău sunt același: cea mai bună tranzacție. Comunic deschis despre prețuri realiste, situația pieței și riscuri. La mine nu există surprize – doar rezultate.",
        navServices: "Servicii",
        navAbout: "Despre mine",
        navReviews: "Recenzii",
        navFaq: "FAQ",
        navContact: "Contact",
        sectionWhyUs: "De ce Marin Imobiliare?",
        sectionAbout: "Despre mine",
        sectionServices: "Serviciile mele",
        sectionReviews: "Recenzii clienți",
        sectionFaq: "Întrebări frecvente",
        sectionContact: "Contact & Consultație",
        contactFormTitle: "Solicită o consultație gratuită",
        contactFormSubmit: "Solicită consultație",
        contactFormSuccess: "Mulțumim! Te contactăm în curând.",
        bannerText: "Acesta este un site demonstrativ. Poți avea unul la fel.",
        bannerCta: "Solicită ofertă",
      },
    },
  },
];

export function getDemoBySlug(slug: string): Demo | undefined {
  return demos.find((d) => d.slug === slug);
}
